Agent First Name,
Agent Last Name,
Agent NPN,
Firm Name,
GA Name,
Group Name,
Group EIN,
Group Zip Code,
Group State,
Quote Effective Date,
Number of eligible employees,
Does eligible employees include collectively bargained union employees?,
Number of collectively bargained union employees?,
Product type,
Medical Eligible count,
Enrolled count for participation,
Total # of Waivers,
# of Retirees Enrolled for Coverage,
# of COBRA/St Continuation Enrolled,
Participation %,
FTE,
MLR TAE Lives,
Requested broker fee,
SIC Code,
SIC Name,
ERISA Indicator,
Group work location Address Line 1,
Group work location Address Line 2,
Group work location City,
Group work location State,
Group work location Zip,
Contract Type (in Months),
TPA,
Current carrier product type,
Are you using Using Aetna  Signature  Administrators®  (ASA),
Is this request for an effective date that is outside of the renewal date?,
PEO (yes/no),
Currently with Aetna Professional Employer Organization (PEO)?,
Is group currently in a Grandfathered Plan?,
Is the group Off cycle?,
Is the group a spinoff?,
Is the group currently with a MEWA?,
Current Funding Arrangement,
Aetna Sales Executive,
Test Group,
Concession Request Details,
Concession Status,
Concession Amount,
Concession Reason
