Job Duties
1	Participating in the requirement gathering sessions, provide analysis support and track them using IBM Rational Jazz Team Server. Review of existing systems configurations and operating methods as well as understanding evolving business needs. 
2	Attending high-level design solution sessions with Enterprise solution Architects and creating Application design specification documents, storing them in SharePoint. This phase establishes the framework for each phase of the software development lifecycle and a miss could impact the entire software solution.
3	Solutioning, designing, programming and unit testing various applications/services using Cognizant tools and best practices/methods which would also include analyzing and achieving quality engineering and assurance of Quoting Center Core Framework Applications using including Java/J2ee, Spring Boot, Microservices, SQL Programming, SOAP, REST API, JDBC.
4	Collaborating with Product Owners and Application Architects to understand business requirements for existing/ new software applications/ tools. Understanding the features (business requirements) by participating in the PI (Program Increment) overview meetings and breaking them into user stories with granular tasks and estimates. Attending PI Planning and contributing to the distribution of user stories across the sprints, Review Epics/User Stories with Product Owners and Quoting Business team and identifying gaps. Revisiting the Epics/User Stories to fix the gaps.
5	Procuring appropriate approvals for Epics/User Stories contracts from Application Architecture teams. Exploring multiple design options and choosing optimal and best high-level/ low-level design. Reviewing designs and solutions with the customers/business teams and provide justifications for the best design during the reviews. Also responsible for demonstrations to end users during sprint/program demos.
6	Participating in technical application support and defect fixing for Quoting Center team. Ensuring that the End Users face minimum disruptions and have continuity of business processes. Solving the critical application issues due to code and functional changes. Performing the technical analysis for the reported defects for the associated applications and interacting with stakeholders for re-design/code refactoring and get their buy-in to address requirement changes and minimize technical debt. Fixing defects raised in staging environments generated due to data inconsistencies. Analyzing and providing Root Cause Analysis (RCA) to management for major incidents.  Checking service health and troubleshooting issues in the cluster environment periodically.
7	Addressing Code Quality & Deployments which would involve ensuring 90% code coverage using Sonar, running scans on Source code to identify potential issues using Eclipse - PMD (Source Code Analyzer tool), Performing code check-in into GitHub daily, Performing CI/CD deployments to staging environment end of every sprint, Performing CI/CD deployments to higher environments.
8	Building the Team functionally to code API for enhancing new features of the frameworks, developing state-of-the-art development tools, and deploying projects via DevOps methodology using tools like Apache Maven, Jenkins build tool, Git-Hub source control and IBM Urban Code Deployment.
